sharding:
  jdbc:
    datasource:
      ds_0:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: org.apache.commons.dbcp.BasicDataSource
        url: jdbc:mysql://localhost:3306/demo_ds_0?useSSL=false&characterEncoding=utf-8
        username: root
      ds_1:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: org.apache.commons.dbcp.BasicDataSource
        url: jdbc:mysql://localhost:3306/demo_ds_1?useSSL=false&characterEncoding=utf-8
        username: root
      names: ds_0,ds_1
    config:
      sharding:
        default-database-strategy:
          inline:
            algorithm-expression: ds_${user_id % 2}
            sharding-column: user_id
        tables:
          t_order:
            actual-data-nodes: ds_${0..1}.t_order_${0..1}
            key-generator-column-name: order_id
            table-strategy:
              inline:
                algorithm-expression: t_order_${order_id % 2}
                sharding-column: order_id
          t_order_item:
            actual-data-nodes: ds_${0..1}.t_order_item_${0..1}
            key-generator-column-name: order_item_id
            table-strategy:
              inline:
                algorithm-expression: t_order_item_${order_id % 2}
                sharding-column: order_id
